version: "3.9"
# TODO: do poprawy ca≈Çy kodnig oraz dodanie docker file 

services:
  mysql:
    container_name: mysqlv2
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: report_maker
      MYSQL_USER: maker
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # - ./infra/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - reports-network

  redis:
    container_name: redis
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - reports-network

  python:
    container_name: python
    build:
      context: .
      dockerfile: ./Dockerfile
      target: python
    # env_file: .env
    depends_on: [mysql, redis]
    ports:
      - "8000:8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000" , "--reload"]
    networks:
      - reports-network

  worker:
    container_name: worker
    build:
      context: .
      dockerfile: ./Dockerfile
      target: python
    # env_file: .env
    depends_on: [mysql, redis]
    command: ["celery", "-A", "app.celery_app:celery", "worker", "--loglevel=INFO", "-Q", "default"]
    networks:
      - reports-network

  node:
    container_name: nodev2
    build:
      context: .
      dockerfile: ./Dockerfile
      target: node
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - shared-dist:/app/dist
    networks:
      - reports-network

  nginx:
    container_name: nginxv2
    build:
      context: .
      dockerfile: ./Dockerfile
      target: nginx
    ports:
      # - "${NGINX_PORT}:${NGINX_PORT}"
      - "80:80"
      - "443:443"
    volumes:
      - shared-dist:/usr/share/nginx/html
    depends_on:
      - node
    networks:
      - reports-network

networks:
  reports-network:
    name: reports-network
    driver: bridge

volumes:
  mysql_data:
  shared-dist:
